### ISSUE TITLE
It works, but only partially 

### ISSUE THREAD

**Issue by fr1sk** [angeloanan/youtube-tv-browser#1]
I managed to connect successfully to youtube.com/tv and link account but when I open YT app on my phone (on the same account) I cannot see the PC that is connected (using your extension). I think that is not related to your extension but youtube restriction itself. Maybe it will be good to just note that in the readme.

**Comment by angeloanan** [comment]
Unfortunately, this is a YouTube restriction and I can't do anything about it. 

I'd suggest to install this extension on another chrome profile, open YouTube and pair it using TV code. That way, you can still control YouTube through your phone. I'll add this to the readme soon:tm:.

Also so sorry for the long reply, I legit just saw this issue today D:
