### ISSUE TITLE
steam deck

### ISSUE THREAD

**Issue by ask-compu** [angeloanan/youtube-tv-browser#3]
it _kinda_ works on steam deck but it doesn't fill the screen and only allows the videos to do up to 480p

**Comment by zlocate** [comment]
Try to use my fork (changed only user agent to PS4)
https://github.com/zlocate/youtube-tv-browser-rework/

**Comment by angeloanan** [comment]
Apologies for not noticing this issue. This has somehow went under my radar :/
I am unable to test for Steam Deck compatibility atm, but I've made an update which allows for 720p+ and HDR playback using the extension.
If it's possible, do help me to test for Steam Deck compatibility. If it works fine, feel free to close this issue!

**Comment by angeloanan** [comment]
Due to inactivity and lack of update, I'm closing this issue.
If the problem still persist after https://github.com/angeloanan/youtube-tv-browser/commit/0bcfba70f0d012c71870d23db7f56521c66ff939, please open a new issue!
