### ISSUE TITLE
Fix extenstion 

### ISSUE THREAD

**Issue by zlocate** [angeloanan/youtube-tv-browser#5]
Now this extension doesn't work with actual youtube version. It may be fixed by changing UA to PS4, than this works well
My fork https://github.com/zlocate/youtube-tv-browser-rework/

**Comment by angeloanan** [comment]
Thanks for the heads up.
I've updated the extension to use an updated TV which allow for 720p+ and HDR playback.

A future note, consider opening a PR for changes like this so I can merge your change upstream.
